language: rust
rust:
  - stable
  - beta
  - nightly

script:
  - ./scripts/build-all.sh
  - cargo test --features nightly
  - cargo bench --features nightly

after_success:
  - sudo apt-get install python-unittest2
  - sudo pip install ghp-import urllib3[secure] autobahntestsuite
  - echo "Running Autobahn TestSuite for client" && ./scripts/autobahn-client.sh
  - echo "Running Autobahn TestSuite for server" && ./scripts/autobahn-server.sh
